import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import {MapPin,CalendarDays,Users,ArrowUpRight,Star,Check,Wifi,Car,UtensilsCrossed,ShieldCheck,BedDouble,Sparkles,Menu,X,Phone,ChevronRight} from "lucide-react";
import "./styles.css";
const rooms=[
["Presidential Suite","King bed · 2 guests · 82 m²","₦420,000","Signature","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=85"],
["Executive Suite","King bed · 2 guests · 58 m²","₦280,000","Executive","https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1400&q=85"],
["Deluxe Room","Queen bed · 2 guests · 38 m²","₦185,000","Deluxe","https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1400&q=85"]];
const amenities=[["24/7 Concierge",ShieldCheck],["High-speed Wi-Fi",Wifi],["Secure Parking",Car],["Fine Dining",UtensilsCrossed],["Housekeeping",Sparkles],["Premium Bedding",BedDouble]];
function App(){const[open,setOpen]=useState(false);return <div className="site">
<header><div className="nav"><a className="brand" href="#"><span className="mark">J</span><span><b>JPEX</b><small>HOTEL & SUITES</small></span></a><nav className={open?"open":""}><a href="#rooms">Suites</a><a href="#experience">Experience</a><a href="#amenities">Amenities</a><a href="#location">Location</a><a href="#contact">Contact</a><a className="navcta" href="#booking">Reserve a stay <ArrowUpRight size={15}/></a></nav><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>
<section className="hero"><div className="ring r1"/><div className="ring r2"/><div className="heroGrid"><div><div className="kicker"><i/>FIVE-STAR HOSPITALITY · ABRAKA</div><h1>A more <em>elevated</em> way to stay.</h1><p>JPEX Hotel & Suites pairs refined rooms, attentive service and a calm sense of luxury in the heart of Abraka.</p><div className="actions"><a className="btn dark" href="#booking">Reserve your stay <ArrowUpRight size={17}/></a><a className="textbtn" href="#rooms">Explore suites <ChevronRight size={17}/></a></div><div className="trust"><span>{[1,2,3,4,5].map(x=><Star key={x} size={14} fill="currentColor"/>)}</span> Exceptional guest experience</div></div><div className="heroVisual"><img src="https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1600&q=90"/><div className="badge"><span><Sparkles size={15}/></span><div><b>JPEX Standard</b><small>Designed for discerning stays</small></div></div><div className="loc"><MapPin size={14}/>Abraka, Delta State</div></div></div>
<div className="booking" id="booking"><div className="bookhead"><div><small>DIRECT RESERVATIONS</small><b>Plan your stay</b></div><span>Best available experience</span></div><div className="bookgrid"><label><CalendarDays/><small>CHECK IN</small><strong>Select date</strong></label><label><CalendarDays/><small>CHECK OUT</small><strong>Select date</strong></label><label><Users/><small>GUESTS</small><strong>2 guests</strong></label><a className="btn yellow" href="#contact">Check availability <ArrowUpRight size={16}/></a></div></div></section>
<section className="proof"><div><b>5-star</b><span>hospitality direction</span></div><div><b>24/7</b><span>guest attention</span></div><div><b>ABRAKA</b><span>Delta State</span></div><div><b>JPEX</b><span>refined by design</span></div></section>
<section className="section intro" id="experience"><div className="twocol"><div><div className="kicker dark"><i/>THE JPEX EXPERIENCE</div><h2>Luxury is how the <em>details</em> make you feel.</h2><p>From the first welcome to the final turn-down, every touchpoint is designed around comfort, privacy and effortless service.</p><a className="textbtn" href="#amenities">Discover the experience <ChevronRight size={17}/></a></div><div className="photo"><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=85"/><div><small>THE ART OF THE STAY</small><b>Quiet spaces. Exceptional comfort.</b></div></div></div></section>
<section className="section rooms" id="rooms"><div className="sectionHead"><div><div className="kicker dark"><i/>ACCOMMODATION</div><h2>Suites made for <em>arrival.</em></h2></div><p>Thoughtfully appointed spaces for business trips, celebrations and unhurried escapes.</p></div><div className="roomgrid">{rooms.map(r=><article className="room" key={r[0]}><div className="roomimg"><img src={r[4]}/><span>{r[3]}</span><button><ArrowUpRight/></button></div><div className="roombody"><div><h3>{r[0]}</h3><p>{r[1]}</p></div><strong>{r[2]}<small>/ night</small></strong></div></article>)}</div></section>
<section className="section amenities" id="amenities"><div><div className="kicker dark"><i/>THE JPEX STANDARD</div><h2>Everything considered.</h2><p>Premium stays are built from the details guests notice — and the ones they simply feel.</p></div><div className="amenitygrid">{amenities.map(([t,I])=><div className="amenity" key={t}><span className="icon"><I size={19}/></span><b>{t}</b><small>Thoughtful service, beautifully delivered.</small></div>)}</div></section>
<section className="section service"><div className="serviceimg"><img src="https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1600&q=88"/></div><div><div className="kicker"><i/>SERVICE, REFINED</div><h2>Arrive. Unwind. <em>Stay beautifully.</em></h2><p>JPEX is designed for guests who value a polished environment, discreet attention and the confidence that everything is in its place.</p><div className="checks">{["Private, comfortable spaces","Attentive guest service","Elegant dining & leisure","A considered stay from arrival to departure"].map(x=><span key={x}><Check size={15}/>{x}</span>)}</div></div></section>
<section className="section location" id="location"><div><div className="kicker dark"><i/>FIND US IN ABRAKA</div><h2>Close to where <em>life happens.</em></h2><p>Positioned in Abraka, Delta State, JPEX is designed as a polished base for business, celebrations and weekend stays.</p><a className="btn dark" href="#contact"><MapPin size={16}/>Get directions</a></div><div className="map"><div className="pin"><MapPin size={20}/><b>JPEX</b><small>Abraka</small></div><label>DELTA STATE · NIGERIA</label></div></section>
<section className="section final" id="contact"><div><div className="kicker"><i/>YOUR NEXT STAY</div><h2>Make your stay <em>JPEX.</em></h2><p>For reservations, enquiries and private arrangements, speak with our team.</p></div><div className="finalactions"><a className="btn yellow" href="https://wa.me/2348051509284">WhatsApp reservations <ArrowUpRight size={17}/></a><a className="phone" href="tel:+2348051509284"><Phone size={16}/>0805 150 9284</a></div></section>
<footer><div className="footerbrand"><span className="mark">J</span><span><b>JPEX</b><small>HOTEL & SUITES</small></span></div><p>Refined hospitality in Abraka, Delta State.</p><div className="copy">© 2026 JPEX Hotel & Suites · 0805 150 9284</div></footer><a className="wa" href="https://wa.me/2348051509284">WA</a></div>}
createRoot(document.getElementById("root")).render(<App/>);